<template>
  <template v-if="page==='dashboard'"><StatCards :items="cards"/><section class="content-grid"><article class="panel"><h2>业务状态分布</h2><div v-for="item in statusRows" :key="item.label" class="metric-row"><span>{{item.label}}</span><div><i :style="{width:item.percent+'%'}"></i></div><b>{{item.value}}</b></div></article><article class="panel"><h2>管理提醒</h2><ul class="notice-list"><li><i class="fa-solid fa-triangle-exclamation"></i><div><strong>{{stats.waitingTotal||0}} 条反馈等待指派</strong><span>建议优先匹配同城市可工作网格员</span></div></li><li><i class="fa-solid fa-flask"></i><div><strong>{{stats.doingTotal||0}} 项任务正在检测</strong><span>可在监督数据页跟踪进度</span></div></li><li><i class="fa-solid fa-chart-line"></i><div><strong>{{stats.badTotal||0}} 条数据达到污染等级</strong><span>已同步至决策者统计端</span></div></li></ul></article></section></template>
  <section v-else-if="page==='feedbacks'" class="panel"><div class="panel-title"><div><h2>公众监督数据</h2><p>完整查看反馈、指派和实测结果。</p></div><button class="secondary" @click="loadAll">刷新</button></div><el-table :data="feedbacks" stripe><el-table-column prop="feedbackNo" label="编号" min-width="165"/><el-table-column prop="province" label="省份"/><el-table-column prop="city" label="城市"/><el-table-column prop="address" label="地址" min-width="180"/><el-table-column label="预估"><template #default="s"><AqiBadge :value="s.row.estimate"/></template></el-table-column><el-table-column prop="workerName" label="网格员"/><el-table-column prop="status" label="状态"/><el-table-column label="最终AQI"><template #default="s"><AqiBadge :value="s.row.finalAqi"/></template></el-table-column></el-table></section>
  <section v-else-if="page==='assign'" class="content-grid assign-layout"><article class="panel"><h2>待指派反馈</h2><div v-for="item in waiting" :key="item.id" class="task-item" :class="{selected:selectedFeedback?.id===item.id}" @click="selectedFeedback=item"><strong>{{item.feedbackNo}}</strong><span>{{item.province}} · {{item.city}}</span><small>{{item.address}}</small></div><p v-if="!waiting.length" class="empty">暂无待指派任务</p></article><article class="panel"><h2>选择网格员</h2><template v-if="selectedFeedback"><p>当前反馈：{{selectedFeedback.city}} · {{selectedFeedback.address}}</p><div v-for="worker in workers" :key="worker.id" class="worker-option" :class="{recommended:worker.city===selectedFeedback.city}"><div><strong>{{worker.name}}</strong><span>{{worker.province}} · {{worker.city}} · {{worker.status}}</span></div><em v-if="worker.city===selectedFeedback.city">本地优先</em><button class="table-action" @click="assign(worker)">指派</button></div></template><p v-else class="empty">请先选择左侧反馈</p></article></section>
  <section v-else-if="page==='workers'" class="panel"><div class="panel-title"><div><h2>网格员管理</h2><p>查看人员所属区域、工作状态和任务负载。</p></div></div><el-table :data="workers" stripe><el-table-column prop="code" label="编号"/><el-table-column prop="name" label="姓名"/><el-table-column prop="province" label="省份"/><el-table-column prop="city" label="城市"/><el-table-column prop="status" label="工作状态"/><el-table-column prop="taskCount" label="累计任务"/></el-table></section>
  <section v-else class="panel"><div class="panel-title"><div><h2>网格区域管理</h2><p>以城市作为最小网格单位，展示覆盖和业务负载。</p></div></div><el-table :data="areas" stripe><el-table-column prop="province" label="省份"/><el-table-column prop="city" label="城市网格"/><el-table-column prop="workerCount" label="网格员数"/><el-table-column prop="feedbackCount" label="反馈数量"/><el-table-column label="运行状态"><template #default><span class="online">运行中</span></template></el-table-column></el-table></section>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {ElMessage} from 'element-plus';import http from '../api/http';import AqiBadge from '../components/AqiBadge.vue';import StatCards from '../components/StatCards.vue';defineProps({page:String});const feedbacks=ref([]),workers=ref([]),areas=ref([]),stats=ref({}),selectedFeedback=ref(null);const waiting=computed(()=>feedbacks.value.filter(x=>x.status==='待指派'));const cards=computed(()=>[{label:'反馈总数',value:stats.value.feedbackTotal,icon:'fa-solid fa-message'},{label:'待指派',value:stats.value.waitingTotal,icon:'fa-solid fa-hourglass-half'},{label:'检测中',value:stats.value.doingTotal,icon:'fa-solid fa-flask'},{label:'已完成',value:stats.value.doneTotal,icon:'fa-solid fa-circle-check'}]);const statusRows=computed(()=>{const total=Math.max(1,stats.value.feedbackTotal||0);return[['待指派',stats.value.waitingTotal||0],['已指派',stats.value.doingTotal||0],['已完成',stats.value.doneTotal||0]].map(([label,value])=>({label,value,percent:value/total*100}))});async function loadAll(){const [f,w,a,s]=await Promise.all([http.get('/feedbacks'),http.get('/workers'),http.get('/areas'),http.get('/stats')]);feedbacks.value=f.data;workers.value=w.data;areas.value=a.data;stats.value=s.data;if(!selectedFeedback.value)selectedFeedback.value=waiting.value[0]}async function assign(worker){await http.post('/assignments',{feedbackId:selectedFeedback.value.id,workerId:worker.id});ElMessage.success(worker.city===selectedFeedback.value.city?'本地指派成功':'异地支援指派成功');selectedFeedback.value=null;await loadAll()}onMounted(loadAll)
</script>
