<template>
  <template v-if="page==='screen'">
    <section class="decision-hero"><div><p>NEPV VISUAL COMMAND CENTER</p><h2>空气质量统计数据可视化大屏</h2><span>严格对应需求陈述书八项统计指标 · 更新时间：{{now}}</span></div><div class="command-status"><i></i><span>数据链路<strong>全部在线</strong></span></div></section>
    <section class="decision-required-kpis"><article><i class="fa-solid fa-satellite-dish"></i><span>检测数量实时统计<strong>{{stats.realTimeDetectionTotal||0}}</strong><small>条实测数据</small></span></article><article><i class="fa-solid fa-border-all"></i><span>全国网格覆盖统计<strong>{{stats.cityCoverage||0}}</strong><small>个城市网格</small></span></article><article><i class="fa-solid fa-map-location-dot"></i><span>省级区域覆盖<strong>{{stats.provinceCoverage||0}}</strong><small>个省级区域</small></span></article><article><i class="fa-solid fa-triangle-exclamation"></i><span>AQI超标累计<strong>{{pollutantTotals.aqi}}</strong><small>条污染数据</small></span></article></section>
    <section class="decision-map-grid"><ChinaCoverageMap :provinces="stats.provinces"/><PollutantProvinceChart :rows="stats.pollutants||[]"/></section>
    <AnalyticsBoard :stats="stats" :show-province="false"/>
  </template>

  <template v-else-if="page==='statistics'">
    <section class="statistics-banner"><div><p>NEPV STATISTICAL DATA</p><h2>浏览统计数据</h2><span>以下八项内容与需求陈述书 NEPV 决策者端逐项对应。</span></div><button class="secondary" @click="load"><i class="fa-solid fa-arrows-rotate"></i> 刷新统计</button></section>
    <section class="requirement-stat-grid"><article v-for="(item,index) in requirementStats" :key="item.label"><b>{{String(index+1).padStart(2,'0')}}</b><i :class="item.icon"></i><span>{{item.label}}</span><strong>{{item.value}}</strong><small>{{item.unit}}</small></article></section>
    <section class="panel"><div class="panel-title"><div><h2>省分组超标统计明细</h2><p>分别统计SO2、CO、PM2.5和最终AQI浓度等级超标累计数量。</p></div><div class="decision-table-tools"><select v-model="provinceFilter"><option value="">全部省份</option><option v-for="name in provinceOptions" :key="name">{{name}}</option></select><select v-model="riskFilter"><option value="">全部风险</option><option value="重点关注">重点关注</option><option value="常态监测">常态监测</option></select><button class="secondary" @click="exportCsv"><i class="fa-solid fa-download"></i> 导出数据</button></div></div><el-table :data="pagedPollutants" stripe><el-table-column prop="province" label="省份" min-width="130"/><el-table-column prop="so2" label="SO2超标"/><el-table-column prop="co" label="CO超标"/><el-table-column prop="pm25" label="PM2.5超标"/><el-table-column prop="aqi" label="AQI等级超标"/><el-table-column label="风险研判"><template #default="s"><span :class="s.row.aqi>1?'risk-label':'normal-label'">{{s.row.aqi>1?'重点关注':'常态监测'}}</span></template></el-table-column></el-table><el-pagination class="table-pagination" v-model:current-page="pollutantPage" :page-size="8" layout="total, prev, pager, next" :total="filteredPollutants.length"/></section>
    <section class="decision-detail-grid"><article class="panel"><h2>AQI指数分布统计</h2><div class="distribution-list"><div v-for="item in levelRows" :key="item.label"><AqiBadge :value="item.label"/><div><i :style="{width:item.percent+'%'}"></i></div><strong>{{item.value}}</strong><small>{{item.percent}}%</small></div></div></article><article class="panel"><h2>覆盖率与实时统计</h2><dl class="coverage-detail"><dt>省级区域覆盖</dt><dd>{{stats.provinceCoverage||0}} 个</dd><dt>城市网格覆盖</dt><dd>{{stats.cityCoverage||0}} 个</dd><dt>空气质量检测总量</dt><dd>{{stats.realTimeDetectionTotal||0}} 条</dd><dt>当前待检测任务</dt><dd>{{stats.doingTotal||0}} 项</dd></dl></article></section>
  </template>

  <section v-else class="report-sheet enhanced-report">
    <header><div><p class="eyebrow">ENVIRONMENTAL DECISION BRIEF</p><h2>空气质量公众监督决策简报</h2><p class="report-date">报告编号：NEPV-{{reportDate}} · 生成时间：{{now}}</p></div><span class="report-mark"><i class="fa-solid fa-leaf"></i>NEPV</span></header>
    <div class="report-summary">本周期累计接收公众监督反馈 <b>{{stats.feedbackTotal||0}}</b> 条，完成现场实测 <b>{{stats.doneTotal||0}}</b> 条，业务闭环率 <b>{{completion}}%</b>；AQI浓度等级超标累计 <b>{{pollutantTotals.aqi}}</b> 条。</div>
    <div class="report-kpis"><article><span>公众参与</span><strong>{{stats.feedbackTotal||0}}</strong><small>累计反馈</small></article><article><span>治理效率</span><strong>{{completion}}%</strong><small>闭环完成率</small></article><article><span>质量水平</span><strong>{{goodRate}}%</strong><small>优良数据占比</small></article></div>
    <section><h3><b>01</b> 综合研判</h3><p>当前公众监督业务已形成“公众上报、属地指派、网格核验、数据汇总、辅助决策”的完整闭环。统计结果显示，各省污染物超标情况存在差异，应结合SO2、CO、PM2.5和最终AQI等级实施分类治理。</p></section>
    <section><h3><b>02</b> 重点问题</h3><ul class="report-findings"><li><i class="fa-solid fa-location-dot"></i><div><strong>区域集中性</strong><span>超标累计较高省份需要保持巡检频次。</span></div></li><li><i class="fa-solid fa-clock"></i><div><strong>处置时效性</strong><span>待指派任务应及时完成属地匹配。</span></div></li><li><i class="fa-solid fa-database"></i><div><strong>数据一致性</strong><span>持续对比公众预估与现场实测结果。</span></div></li></ul></section>
    <section><h3><b>03</b> 治理建议</h3><ol><li>针对各省主要超标污染物制定差异化巡检方案。</li><li>任务积压时启动异地支援，缩短反馈处置周期。</li><li>将八项统计指标纳入月度环境治理评价。</li></ol></section><div class="report-sign">东软环保公众监督系统 · NEPV决策支持端</div>
  </section>
</template>

<script setup>
import{computed,onMounted,ref,watch}from'vue';import http from '../api/http';import AqiBadge from '../components/AqiBadge.vue';import AnalyticsBoard from '../components/AnalyticsBoard.vue';import ChinaCoverageMap from '../components/ChinaCoverageMap.vue';import PollutantProvinceChart from '../components/PollutantProvinceChart.vue'
defineProps({page:String});const stats=ref({}),pollutantPage=ref(1),provinceFilter=ref(''),riskFilter=ref('');const now=new Date().toLocaleString('zh-CN',{hour12:false}),reportDate=new Date().toISOString().slice(0,10).replaceAll('-','')
const pollutantTotals=computed(()=>{const rows=stats.value.pollutants||[];return rows.reduce((sum,row)=>({so2:sum.so2+Number(row.so2||0),co:sum.co+Number(row.co||0),pm25:sum.pm25+Number(row.pm25||0),aqi:sum.aqi+Number(row.aqi||0)}),{so2:0,co:0,pm25:0,aqi:0})})
const requirementStats=computed(()=>[{label:'省分组-SO2浓度超标累计',value:pollutantTotals.value.so2,unit:'条',icon:'fa-solid fa-industry'},{label:'省分组-CO浓度超标累计',value:pollutantTotals.value.co,unit:'条',icon:'fa-solid fa-car-side'},{label:'省分组-PM2.5浓度超标累计',value:pollutantTotals.value.pm25,unit:'条',icon:'fa-solid fa-smog'},{label:'省分组-AQI等级超标累计',value:pollutantTotals.value.aqi,unit:'条',icon:'fa-solid fa-triangle-exclamation'},{label:'AQI指数分布统计',value:Object.keys(stats.value.levels||{}).length,unit:'个等级',icon:'fa-solid fa-chart-pie'},{label:'AQI指数趋势统计',value:(stats.value.trend||[]).length,unit:'个时点',icon:'fa-solid fa-chart-line'},{label:'空气质量检测数量实时统计',value:stats.value.realTimeDetectionTotal||0,unit:'条',icon:'fa-solid fa-satellite-dish'},{label:'全国网格覆盖率统计',value:stats.value.cityCoverage||0,unit:'个城市',icon:'fa-solid fa-border-all'}])
const levelRows=computed(()=>{const entries=Object.entries(stats.value.levels||{}),total=entries.reduce((sum,item)=>sum+Number(item[1]),0);return entries.map(([label,value])=>({label,value,percent:Math.round(Number(value)/Math.max(1,total)*100)}))})
const provinceOptions=computed(()=>(stats.value.pollutants||[]).map(row=>row.province));const filteredPollutants=computed(()=>(stats.value.pollutants||[]).filter(row=>(!provinceFilter.value||row.province===provinceFilter.value)&&(!riskFilter.value||(row.aqi>1?'重点关注':'常态监测')===riskFilter.value)));const pagedPollutants=computed(()=>filteredPollutants.value.slice((pollutantPage.value-1)*8,pollutantPage.value*8));const completion=computed(()=>Math.round((stats.value.doneTotal||0)/Math.max(1,stats.value.feedbackTotal||0)*100));const goodRate=computed(()=>Math.round((stats.value.goodTotal||0)/Math.max(1,stats.value.doneTotal||0)*100))
function exportCsv(){const header=['省份','SO2超标','CO超标','PM2.5超标','AQI等级超标','风险研判'];const rows=filteredPollutants.value.map(row=>[row.province,row.so2,row.co,row.pm25,row.aqi,row.aqi>1?'重点关注':'常态监测']);const csv='\ufeff'+[header,...rows].map(line=>line.join(',')).join('\n');const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));link.download=`NEPV省份超标统计-${reportDate}.csv`;link.click();URL.revokeObjectURL(link.href)}
watch([provinceFilter,riskFilter],()=>pollutantPage.value=1)
async function load(){stats.value=(await http.get('/stats')).data}onMounted(load)
</script>
